### ISSUE TITLE
Needs to be Updated for GCM

### ISSUE THREAD

**Issue by crazydavy-zz** [mokriya-org/zoom-us-ios-sdk-pod#1]
From the ZOOM Sdk.

"To align with Zoom’s recent announcement pertaining to our security initiative, Zoom Client SDKs have added AES 256-bit GCM encryption support, which provides more protection for meeting data and greater resistance to tampering. The system-wide account enablement of AES 256-bit GCM encryption will take place on June 01, 2020. You are strongly recommended to start the required upgrade to this latest version 4.6.21666.0428 at your earliest convenience. Please note that any Client SDK versions below 4.6.21666.0428 will no longer be operational from June 01."

I could go manual, but it seems like it'd be better to update this pod...  @jimji1005 
If you are not updating this anymore, I can fork as well... Any preferences?

**Comment by jimji1005** [comment]
@crazydavy thanks for the reminder, just updated it with v4.6.21666.0428

**Comment by KawaljeetSBagga** [comment]
Hey thank you so much. I was also gonna remind you that. Job already done :D

**Comment by KawaljeetCuelogic** [comment]
@jimji1005 Can you consider updating the zoom SDK to match the latest version `v5.2.42037.1112` ?
I am testing on the M1 machine. It seems that version of ZoomSDK is old and not supported for the M1 machine.
